# Generated by Django 4.2.7 on 2026-02-18 16:26

import config.storages
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('staff', 'Staff')], default='super_admin', help_text='User role determines access level', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='User profile picture', null=True, storage=config.storages.R2MediaStorage(), upload_to=utils.user_profile_image_path)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('shop', models.ForeignKey(blank=True, help_text='Shop this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='settings.shop')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('manage_users', 'Manage Users'), ('view_users', 'View Users'), ('create_users', 'Create Users'), ('edit_users', 'Edit Users'), ('delete_users', 'Delete Users'), ('manage_shops', 'Manage Shops'), ('view_shops', 'View Shops'), ('create_shops', 'Create Shops'), ('edit_shops', 'Edit Shops'), ('delete_shops', 'Delete Shops'), ('manage_inventory', 'Manage Inventory'), ('view_inventory', 'View Inventory'), ('create_inventory', 'Create Inventory'), ('edit_inventory', 'Edit Inventory'), ('delete_inventory', 'Delete Inventory'), ('manage_sales', 'Manage Sales'), ('view_sales', 'View Sales'), ('create_sales', 'Create Sales'), ('edit_sales', 'Edit Sales'), ('delete_sales', 'Delete Sales'), ('view_reports', 'View Reports'), ('manage_reports', 'Manage Reports'), ('manage_settings', 'Manage Settings'), ('view_settings', 'View Settings'), ('all_permissions', 'All Permissions')], help_text='Specific permission granted to this user', max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
