# Generated by Django 4.2.7 on 2026-02-18 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(help_text='Shop name', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Shop address', null=True)),
                ('phone', models.CharField(blank=True, help_text='Shop phone', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Shop email', max_length=254, null=True)),
                ('tax_enabled', models.BooleanField(default=True, help_text='Enable tax calculations')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=17.0, help_text='Tax percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is shop active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['shop_name'],
            },
        ),
    ]
