# Generated by Django 4.2.7 on 2026-02-18 16:26

import config.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('is_active', models.BooleanField(default=True, help_text='Is category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, help_text='Shop this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='settings.shop')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ComputerBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand name (e.g., Dell, HP, Apple)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is brand active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(help_text='Shop this brand belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='computer_brands', to='settings.shop')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Model name (e.g., XPS 15, MacBook Pro)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is model active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Related brand', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='inventory.computerbrand')),
                ('shop', models.ForeignKey(help_text='Shop this model belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='computer_models', to='settings.shop')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'unique_together': {('shop', 'brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('item_code', models.CharField(blank=True, help_text='Auto-generated item code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('min_stock_level', models.PositiveIntegerField(default=5, help_text='Minimum stock level for alerts')),
                ('is_active', models.BooleanField(default=True, help_text='Is product active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('shop', models.ForeignKey(blank=True, help_text='Shop this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='settings.shop')),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Supplier name', max_length=100)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=100)),
                ('phone', models.CharField(help_text='Phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Business address')),
                ('tax_number', models.CharField(blank=True, help_text='NTN/STRN number', max_length=50)),
                ('payment_terms', models.CharField(choices=[('cash', 'Cash on Delivery'), ('credit_15', '15 Days Credit'), ('credit_30', '30 Days Credit'), ('credit_45', '45 Days Credit'), ('advance', 'Advance Payment')], default='cash', help_text='Payment terms', max_length=20)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Supplier rating (1-5)')),
                ('is_active', models.BooleanField(default=True, help_text='Is supplier active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(help_text='Shop this supplier belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='settings.shop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerRepair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=100)),
                ('customer_phone', models.CharField(help_text='Customer phone', max_length=15)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email', max_length=254)),
                ('brand', models.CharField(help_text='Computer brand', max_length=100)),
                ('model', models.CharField(help_text='Computer model', max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Computer color', max_length=50)),
                ('problem_description', models.TextField(help_text='Problem description')),
                ('repair_type', models.CharField(help_text='Type of repair (screen, battery, etc.)', max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated repair cost', max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, help_text='Actual repair cost', max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, help_text='Advance payment', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting_parts', 'Waiting for Parts'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Repair status', max_length=20)),
                ('received_date', models.DateTimeField(auto_now_add=True, help_text='Date received')),
                ('estimated_completion_date', models.DateField(blank=True, help_text='Estimated completion date', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('delivered_date', models.DateField(blank=True, help_text='Date delivered', null=True)),
                ('assigned_technician', models.CharField(blank=True, help_text='Assigned technician', max_length=100)),
                ('repair_notes', models.TextField(blank=True, help_text='Internal repair notes')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes for customer')),
                ('under_warranty', models.BooleanField(default=False, help_text='Is repair under warranty?')),
                ('warranty_period', models.PositiveIntegerField(default=30, help_text='Warranty period in days')),
                ('shop', models.ForeignKey(help_text='Shop this repair belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='computer_repairs', to='settings.shop')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='ComputerPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=100)),
                ('customer_phone', models.CharField(help_text='Customer phone', max_length=15)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email', max_length=254)),
                ('id_card_number', models.CharField(blank=True, help_text='Customer ID card number', max_length=20)),
                ('color', models.CharField(blank=True, help_text='Computer color', max_length=50, null=True)),
                ('serial_number', models.CharField(help_text='Serial number', max_length=50)),
                ('asset_tag', models.CharField(blank=True, help_text='Asset tag number', max_length=50)),
                ('computer_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('all_in_one', 'All-in-One'), ('workstation', 'Workstation')], default='laptop', help_text='Computer type', max_length=15)),
                ('ram', models.CharField(blank=True, help_text='RAM (e.g., 16GB DDR4)', max_length=20)),
                ('storage', models.CharField(blank=True, help_text='Storage (e.g., 512GB SSD)', max_length=30)),
                ('storage_type', models.CharField(blank=True, help_text='Storage type (SSD/HDD)', max_length=20)),
                ('display_size', models.CharField(blank=True, help_text='Display size (e.g., 15.6 inch)', max_length=20)),
                ('graphics', models.CharField(blank=True, help_text='Graphics card', max_length=50)),
                ('processor', models.CharField(blank=True, help_text='Processor (e.g., Intel i7, AMD Ryzen)', max_length=50)),
                ('operating_system', models.CharField(blank=True, help_text='Operating system', max_length=30)),
                ('physical_condition', models.TextField(blank=True, help_text='Physical condition description')),
                ('functional_condition', models.TextField(blank=True, help_text='Functional condition description')),
                ('grade', models.CharField(choices=[('a', 'Grade A (Excellent)'), ('b', 'Grade B (Good)'), ('c', 'Grade C (Fair)'), ('d', 'Grade D (Poor)')], help_text='Device condition grade', max_length=10)),
                ('box_packed', models.BooleanField(default=False, help_text='Comes with original box?')),
                ('accessories_included', models.TextField(blank=True, help_text='Included accessories')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase price', max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True, help_text='Date of purchase')),
                ('notes', models.TextField(blank=True, help_text='Purchase notes')),
                ('front_photo', models.ImageField(blank=True, help_text='Front view photo', null=True, storage=config.storages.R2MediaStorage(), upload_to=utils.computer_purchase_photo_path)),
                ('back_photo', models.ImageField(blank=True, help_text='Back view photo', null=True, storage=config.storages.R2MediaStorage(), upload_to=utils.computer_purchase_photo_path)),
                ('id_card_front', models.ImageField(blank=True, help_text='ID card front photo', null=True, storage=config.storages.R2MediaStorage(), upload_to=utils.computer_purchase_photo_path)),
                ('id_card_back', models.ImageField(blank=True, help_text='ID card back photo', null=True, storage=config.storages.R2MediaStorage(), upload_to=utils.computer_purchase_photo_path)),
                ('warranty_status', models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer Warranty'), ('extended', 'Extended Warranty'), ('no_warranty', 'No Warranty'), ('expired', 'Expired Warranty')], help_text='Warranty status', max_length=20)),
                ('warranty_expiry', models.DateField(blank=True, help_text='Warranty expiry date', null=True)),
                ('sold', models.BooleanField(default=False, help_text='Is computer sold?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Computer brand', on_delete=django.db.models.deletion.CASCADE, to='inventory.computerbrand')),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('handled_by', models.ForeignKey(help_text='Staff member who handled the purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(help_text='Computer model', on_delete=django.db.models.deletion.CASCADE, to='inventory.computermodel')),
                ('shop', models.ForeignKey(help_text='Shop this purchase belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='computer_purchases', to='settings.shop')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='ComputerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Computer device image', storage=config.storages.R2MediaStorage(), upload_to=utils.computer_image_path)),
                ('is_main', models.BooleanField(default=False, help_text='Is this the main image?')),
                ('caption', models.CharField(blank=True, help_text='Image caption or description', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer_purchase', models.ForeignKey(help_text='Computer purchase this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.computerpurchase')),
                ('shop', models.ForeignKey(help_text='Shop this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='computer_images', to='settings.shop')),
            ],
            options={
                'ordering': ['-is_main', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(help_text='Date of purchase')),
                ('batch_number', models.CharField(blank=True, help_text='Batch/Lot number', max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase price per unit', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='Total quantity purchased')),
                ('remaining_quantity', models.PositiveIntegerField(default=0, help_text='Remaining quantity available for sale')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (for perishable items)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Purchase notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(help_text='Staff member who handled the purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Related product', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.product')),
                ('shop', models.ForeignKey(help_text='Shop this purchase belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='product_purchases', to='settings.shop')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier for this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
                'unique_together': {('product', 'batch_number')},
            },
        ),
    ]
