# Generated by Django 4.2.7 on 2026-02-18 16:26

import config.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('phone', models.CharField(help_text='Customer phone number', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Customer email', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Customer address')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current balance (positive = customer owes, negative = shop owes)', max_digits=10)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, help_text='Total purchase amount', max_digits=10)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, help_text='Total payment amount', max_digits=10)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding amount', max_digits=10)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular'), ('wholesale', 'Wholesale'), ('vip', 'VIP')], default='regular', help_text='Customer type', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Customer notes')),
                ('profile_image', models.ImageField(blank=True, help_text='Customer profile picture', null=True, storage=config.storages.R2MediaStorage(), upload_to=utils.customer_profile_image_path)),
                ('is_active', models.BooleanField(default=True, help_text='Is customer active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(help_text='Report date')),
                ('total_outstanding', models.DecimalField(decimal_places=2, help_text='Total outstanding amount', max_digits=10)),
                ('days_overdue', models.IntegerField(default=0, help_text='Days since last payment')),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of last payment', null=True)),
                ('last_purchase_date', models.DateField(blank=True, help_text='Date of last purchase', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_outstanding', 'customer__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Transaction type', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Balance before transaction', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after transaction', max_digits=10)),
                ('description', models.CharField(help_text='Transaction description', max_length=255)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Transaction date')),
                ('notes', models.TextField(blank=True, help_text='Transaction notes')),
                ('customer', models.ForeignKey(help_text='Related customer', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer')),
                ('recorded_by', models.ForeignKey(help_text='Staff who recorded transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
