# Generated by Django 4.2.7 on 2026-02-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Related sale (for debit transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='shop',
            field=models.ForeignKey(help_text='Shop this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='settings.shop'),
        ),
        migrations.AddField(
            model_name='customerduereport',
            name='customer',
            field=models.ForeignKey(help_text='Related customer', on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerduereport',
            name='shop',
            field=models.ForeignKey(help_text='Shop this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_due_reports', to='settings.shop'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(help_text='Shop this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='settings.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='customerduereport',
            unique_together={('customer', 'report_date')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('shop', 'phone')},
        ),
    ]
