# Generated by Django 4.2.7 on 2026-02-18 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('shop_created', 'Shop Created'), ('shop_updated', 'Shop Updated'), ('shop_deleted', 'Shop Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('password_changed', 'Password Changed')], help_text='Type of action performed', max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('permission', 'Permission'), ('system', 'System')], help_text='Type of resource affected', max_length=20)),
                ('resource_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected resource', null=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='logs_auditl_user_id_305f98_idx'), models.Index(fields=['resource_type', 'resource_id'], name='logs_auditl_resourc_52fc75_idx'), models.Index(fields=['timestamp'], name='logs_auditl_timesta_630212_idx')],
            },
        ),
    ]
