# Generated by Django 4.2.7 on 2026-02-18 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_number', models.CharField(blank=True, help_text='Auto-generated sale number', max_length=50, unique=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, default='Walk-in Customer', help_text='Walk-in customer name', max_length=100)),
                ('customer_phone', models.CharField(blank=True, default='N/A', help_text='Customer phone number', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before discount and tax', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final total amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('credit', 'Credit'), ('bank_transfer', 'Bank Transfer')], default='cash', help_text='Payment method used', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by customer', max_digits=10)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, help_text='Change given to customer', max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, help_text='Total profit from this sale', max_digits=10)),
                ('is_completed', models.BooleanField(default=True, help_text='Is sale completed?')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Is sale cancelled?')),
                ('notes', models.TextField(blank=True, help_text='Sale notes or comments')),
                ('receipt_printed', models.BooleanField(default=False, help_text='Has receipt been printed?')),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt number for thermal printer', max_length=50)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('shop', models.ForeignKey(help_text='Shop this sale belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='settings.shop')),
                ('sold_by', models.ForeignKey(help_text='Staff member who made the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('credit', 'Credit'), ('bank_transfer', 'Bank Transfer')], default='cash', help_text='Payment method', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('received_by', models.ForeignKey(help_text='Staff who received payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(help_text='Related sale', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
                ('shop', models.ForeignKey(help_text='Shop this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='settings.shop')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Product name at time of sale', max_length=255)),
                ('product_item_code', models.CharField(blank=True, help_text='Product item code at time of sale', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of sale', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity sold')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost price at time of sale', max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, help_text='Profit from this item', max_digits=10)),
                ('computer_purchase', models.ForeignKey(blank=True, help_text='Computer purchase (for computer sales)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.computerpurchase')),
                ('product', models.ForeignKey(blank=True, help_text='Product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('product_purchase', models.ForeignKey(blank=True, help_text='Product purchase batch (for batch tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productpurchase')),
                ('sale', models.ForeignKey(help_text='Related sale', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.sale')),
                ('shop', models.ForeignKey(help_text='Shop this sale item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='settings.shop')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
